### ISSUE TITLE
Add CSS setup

### ISSUE THREAD

**Issue by marcoeh** [wearelucid/lucid-nuxt-2021#2]

**Comment by marcoeh** [comment]
@FabianEllenberger: Because of [this](https://github.com/sasstools/sass-lint#this-project-is-currently-unmaintained---last-developmentstable-release-october-2017) i would vote for [stylelint](https://stylelint.io/). Might be worth to check out the [nuxt module](https://github.com/nuxt-community/stylelint-module) and use a [decent configuration](https://github.com/bjankord/stylelint-config-sass-guidelines) with it.

**Comment by marcoeh** [comment]
Found this article:
> stylelint + stylelint-scss offer a very equivalent rule set compared to the scss-lint rules which Hugo Giraudel recommends in Sass Guidelines.

https://medium.com/@bjankord/how-to-lint-scss-with-stylelint-dc87809a9878

So probably worth some research what the best config would be for us or if `stylelint`s standard config with `stylelint-scss` is the way to go.
https://github.com/stylelint/awesome-stylelint#configs

**Comment by FabianEllenberger** [comment]
> Found this article:
> 
> > stylelint + stylelint-scss offer a very equivalent rule set compared to the scss-lint rules which Hugo Giraudel recommends in Sass Guidelines.
> 
> https://medium.com/@bjankord/how-to-lint-scss-with-stylelint-dc87809a9878
> 
> So probably worth some research what the best config would be for us or if `stylelint`s standard config with `stylelint-scss` is the way to go.
> https://github.com/stylelint/awesome-stylelint#configs

Good point, i just saw the stylelint nuxt-module when i was looking for the style-resources module.
I read the medium article, based on that i would give this [config](https://github.com/bjankord/stylelint-config-sass-guidelines) a try. Also as you mentioned there are a lot of [nice configs](https://github.com/stylelint/awesome-stylelint#configs) to check out.

I will give it a go and see what could/would fit our needs 👍 .

**Comment by marcoeh** [comment]
Sticking to a standard makes sense to me. Adding additional configs if we really need them. There should also be extensions available for code editors to lint files on save and on paste. I would try to rely on those and not disable order rules for example.

**Comment by marcoeh** [comment]
Closed by #27
