### ISSUE TITLE
Medium breakpoint

### ISSUE THREAD

**Issue by mornir** [wearelucid/lucid-nuxt-2021#50]
Hey!

Just a thought: wouldn't it make sense to include the standard iPad in the medium breakpoint?
https://github.com/wearelucid/lucid-nuxt-2021/blob/main/configs/breakpoints.json#L5

I suggest changing `834px` to `768px`. Or do you think that `768px` is too close to `375px`?

Cheers

**Comment by FabianEllenberger** [comment]
> Hey!
> 
> Just a thought: wouldn't it make sense to include the standard iPad in the medium breakpoint?
> https://github.com/wearelucid/lucid-nuxt-2021/blob/main/configs/breakpoints.json#L5
> 
> I suggest changing `834px` to `768px`. Or do you think that `768px` is too close to `375px`?
> 
> Cheers

Currently it will be exposed like this: https://github.com/wearelucid/lucid-nuxt-2021/blob/main/configs/breakpoints.mjs
this will also be very customizable per project needs.
